# Generated by Django 3.1.5 on 2021-02-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=5, max_digits=5)),
                ('longitud', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
    ]
