# Generated by Django 3.1.5 on 2021-03-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacion',
            name='latitud',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='longitud',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
